version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    # Comment the two following lines for production
    volumes:
      - .:/outstagram
    links:
      - db
      - cache
  db:
    image: mysql
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "outstagram"
    ports:
      - "33060:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
  cache:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
volumes:
  mysql: