version: '3'
services:
  web_1:
    build: .
    environment:
      PORT: "5001"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: gin -p 5000 -a 5001 run app.go
    # Comment the two following lines for production
    volumes:
      - .:/outstagram
    links:
      - db
      - cache
  web_2:
    build: .
    environment:
      PORT: "6001"
    ports:
      - "6969:6969"
    expose:
      - "6969"
    command: gin -p 6969 -a 6001 run app.go
    # Comment the two following lines for production
    volumes:
      - .:/outstagram
    links:
      - db
      - cache
  db:
    image: mysql
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "outstagram"
    ports:
      - "33060:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
  cache:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
volumes:
  mysql: